name: icqsol_compose_shapes
owner: iuc
description: |
  Contains a tool that creates a shape composed of any number of selected shapes.
homepage_url: https://github.com/pletzer/icqsol
long_description: |
  Creates a shape composed of any number of selected shapes where the composition
  is based on a mathematical expression consisting of +, - and * operations.  The
  + operator results in a union of shapes, the - operator removes a shape and the
  * operator results in an intersection of shapes.
remote_repository_url:
type: unrestricted
categories:
- Constructive Solid Geometry
