name: icqsol_rotate_shape
owner: iuc
description: Contains a tool that rotates a shape.
homepage_url: https://github.com/gregvonkuster/galaxy-csg
long_description: |
  Contains a tool that applies a rotation by a given angle about an arbitrary axis.
remote_repository_url: https://github.com/gregvonkuster/galaxy-csg
type: unrestricted
categories:
- Constructive Solid Geometry
