name: icqsol_solve_laplace
owner: greg
description: |
  Contains a tool that computes the jump of normal electric field.
homepage_url: https://github.com/gregvonkuster/galaxy-csg
long_description: |
  Contains a tool that computes the jump of normal electric field given a
  potential field on the surface of a shape.
remote_repository_url: https://github.com/gregvonkuster/galaxy-csg/tree/master/tools/icqsol_solve_laplace
type: unrestricted
categories:
- Constructive Solid Geometry
