name: icqsol_translate_shape
owner: greg
description: Contains a tool that translates a shape to a new position.
homepage_url: https://github.com/gregvonkuster/galaxy-csg
long_description: |
  Contains a tool that applies translation operations to a shape by adding a displacement
  to each coordinate. 
remote_repository_url: https://github.com/gregvonkuster/galaxy-csg
type: unrestricted
categories:
- Constructive Solid Geometry
