name: icqsol_refine_shape
owner: greg
description: |
  Contains a tool that refines a shape to a specified level resulting in a more detailed shape.
homepage_url: https://github.com/gregvonkuster/galaxy-csg
long_description: |
  Contains a tool that refines a shape to a specified level resulting in a more detailed shape.
  A middle point is added to each edge and to the center of each of the shape's polygons for
  each level of refinement.
remote_repository_url: https://github.com/gregvonkuster/galaxy-csg
type: unrestricted
categories:
- Constructive Solid Geometry
